// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHqNaL4_qjC2wYPnCF8q_ResyismfOPog',
    appId: '1:1001335563704:web:21b764a1eeadaf3a225b4d',
    messagingSenderId: '1001335563704',
    projectId: 'navigo-37916',
    authDomain: 'navigo-37916.firebaseapp.com',
    storageBucket: 'navigo-37916.firebasestorage.app',
    measurementId: 'G-FN1CY827SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGu0Y95pPHdz0E6eBsbc2xHSsihE26D9s',
    appId: '1:1001335563704:android:202f35def88f5077225b4d',
    messagingSenderId: '1001335563704',
    projectId: 'navigo-37916',
    storageBucket: 'navigo-37916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1OxBiq9gafghOFY-u-Zs0pSDXaNynOI',
    appId: '1:1001335563704:ios:974a38c9a73fd0b2225b4d',
    messagingSenderId: '1001335563704',
    projectId: 'navigo-37916',
    storageBucket: 'navigo-37916.firebasestorage.app',
    iosClientId: '1001335563704-ub8kgugf0f2roh38pdo0lc7jvsvmm967.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1OxBiq9gafghOFY-u-Zs0pSDXaNynOI',
    appId: '1:1001335563704:ios:974a38c9a73fd0b2225b4d',
    messagingSenderId: '1001335563704',
    projectId: 'navigo-37916',
    storageBucket: 'navigo-37916.firebasestorage.app',
    iosClientId: '1001335563704-ub8kgugf0f2roh38pdo0lc7jvsvmm967.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHqNaL4_qjC2wYPnCF8q_ResyismfOPog',
    appId: '1:1001335563704:web:54efbab62306c09e225b4d',
    messagingSenderId: '1001335563704',
    projectId: 'navigo-37916',
    authDomain: 'navigo-37916.firebaseapp.com',
    storageBucket: 'navigo-37916.firebasestorage.app',
    measurementId: 'G-SF0PJZFM81',
  );

}